# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
react:
  title: Code Crazy
  name: Jack Coy
  menu_right_subtitle: Blogger | Software Engineer
  avatar: /static/img/avatar.jpg
  logo: /static/img/code_crazy_logo.png
  email: ''
  description: > # this means to ignore newlines until "baseurl:"
    Extreme Programming Consultant since 2012. Experience in varying
    technical domains such as: Analytical Desktop Software, ETL Data Pipelines,
    Web Apps, and Android/iOS Apps. I consider myself an aspiring expert on
    Testing, Automation, Lean Software Development, and Pairing.
  baseurl: "" # the subpath of your site, e.g. /blog
  url: "https://jackman3005.github.io" # the base hostname & protocol for your site
  permalink: /posts/:title
  social:
    twitter: http://twitter.com/jackman3005
    github: http://github.com/jackman3005
    facebook: http://facebook.com/jackman3005
    code: http://github.com/jackman3005/jackman3005.github.io #livecoding.tv handle
    rss: feed.xml


title: Code Crazy
name: Jack Coy
menu_right_subtitle: Blogger | Software Engineer
avatar: /static/img/avatar.jpg
logo: /static/img/code_crazy_logo.png
email: ''
description: > # this means to ignore newlines until "baseurl:"
    Extreme Programming Consultant since 2012. Experience in varying
    technical domains such as: Analytical Desktop Software, ETL Data Pipelines,
    Web Apps, and Android/iOS Apps. I consider myself an aspiring expert on
    Testing, Automation, Lean Software Development, and Pairing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jackman3005.github.io" # the base hostname & protocol for your site
permalink: /posts/:title


twitter_username: jackman3005
github_username: Jackman3005


# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

source: src
destination: docs

assets:
  compress:
    css: sass
    js: false

  autowrite: true
  cache: .asset-cache
  cache_type: filesystem
  cdn: www.example.com
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: true

  assets:
    - "*.png"
    - "bundle.css"
    - "bundle.js.map"
    - "*.svg"
    - "*.eof"
    - "*.ttf"

  sources:
    - src/_assets/css
    - src/_assets/fonts
    - src/_assets/img
    - src/_assets/projects

  features:
    liquid: false
    integrity: true
    automatic_img_size: true
    automatic_img_alt : true

exclude: ['node_modules', 'Gemfile', '.asset-cache', 'build-prod.sh', 'build-dev.sh']

plugins:
  - jekyll-assets
  - jekyll_pages_api
  - jekyll-react
